name: CI

on:
  push:
    branches: '**'
    tags-ignore: '**'
    paths:
      - 'lib/**'
      - 'GhostServer/**'
      - 'Makefile'
      - .github/workflows/CI.yaml
  pull_request:
    branches: '**'
    paths:
      - 'lib/**'
      - 'GhostServer/**'
      - 'Makefile'
      - .github/workflows/CI.yaml
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-lin:
    name: Linux Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - name: Install Dependencies
        run: sudo apt-get install -y g++-10-multilib qtbase5-dev
      - name: Build
        run: make -j$(nproc)
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GhostServer-linux
          path: |
            ./ghost_server
            ./ghost_server_cli
          if-no-files-found: error
  # todo: windows action
